targets:
  $default:
    builders:
      ngdart:
        generate_for:
          exclude:
            - "lib/src/build.dart"
            - "lib/src/compiler/**"
            - "lib/src/source_gen/**"

builders:
  ngdart:
    import: "package:ngdart/src/build.dart"
    builder_factories:
      - templatePlaceholder
      - templateCompiler
      - stylesheetCompiler
    auto_apply: dependents
    applies_builders:
      - "ngdart|placeholder_cleanup"
      - "ngdart|component_source_cleanup"
    # See https://github.com/angulardart/angular/issues/988.
    is_optional: true
    required_inputs:
      - ".css"
    build_extensions:
      .css:
        - ".css.dart"
        - ".css.shim.dart"
      .dart:
        - ".template.dart"
post_process_builders:
  placeholder_cleanup:
    import: "package:ngdart/src/build.dart"
    builder_factory: "placeholderCleanup"
  component_source_cleanup:
    import: "package:ngdart/src/build.dart"
    builder_factory: "componentSourceCleanup"
    defaults:
      generate_for: ["lib/**"]
      release_options:
        enabled: true
