name: ngdart
version: 7.1.1
description: >-
  Fast and productive web framework by Google.
  Separate, but similar to the JavaScript framework with a similar name.
repository: https://github.com/angulardart-community/angular
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  # Runtime (or runtime *and* the compiler).
  built_collection: ^5.0.0
  built_value: ^8.0.0
  collection: ^1.15.0
  intl: ^0.17.0
  js: ^0.6.3
  logging: ^1.0.0
  # to fix bug https://github.com/angulardart-community/angular/issues/67
  meta: '>=1.3.0 <1.10.0' #^1.3.0

  stack_trace: ^1.10.0
  stream_transform: ^2.0.0

  # Allowing a tiny bit of wiggle here to allow publishing minor updates
  ngast: ^2.1.4
  ngcompiler: ^2.1.2
  ##########################################################################

  build: ^2.0.0
  build_config: ^1.0.0
  code_builder: ^4.0.0
  csslib: ^0.17.0
  path: ^1.8.0
  quiver: ^3.0.0
  source_gen: ^1.0.0
  source_span: ^1.8.0

dev_dependencies:
  # Compiler. Eventually we want to move these to angular_compiler.
  analyzer: ^4.2.0
  lints: ^2.0.0
  build_runner: ^2.0.0
